version: '3.8'

services:
  # 1. Autoroute (MQTT)
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: microgrid_mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  # 2. L'historique (BDD InfluxDB)
  influxdb:
    image: influxdb:2.7
    container_name: microgrid_db
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=smartgrid2026
      - DOCKER_INFLUXDB_INIT_ORG=voltis_org
      - DOCKER_INFLUXDB_INIT_BUCKET=voltis_bucket

  # 3. Le tableau de bord (Grafana)
  grafana:
    image: grafana/grafana:latest
    container_name: microgrid_dashboard
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin